# Generated by Django 5.0.3 on 2024-04-27 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anonymoususer',
            old_name='prescription_file',
            new_name='prescription',
        ),
    ]
