# Generated by Django 5.0.3 on 2024-04-27 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_prescription_file_anonymousappointments_prescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='prescription_file',
            new_name='prescription',
        ),
    ]
